version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: MAGMA
      VERSION: 1.16.5
    volumes:
      - data:/data
volumes:
  data: {}